apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-passbolt
  labels:
    app: passbolt
    tier: mysql
spec:
  selector:
    matchLabels:
      app: passbolt
      tier: mysql
  serviceName: mariadb-service
  template:
    metadata:
      labels:
        app: passbolt
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.5
        name: mariadb
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: mysql-user
              name: mariadb-configmap
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mysql-database
              name: mariadb-configmap
        ports:
        - containerPort: 3306
          name: passbolt-mysql
        volumeMounts:
        - name: passbolt-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: passbolt-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: passbolt-mysql-pvc
