apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: passbolt
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: passbolt
    tier: mysql
  clusterIP: None
