apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passbolt-mysql-pvc
  labels:
    app: passbolt
spec:
  storageClassName: storageName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
