apiVersion: v1
kind: Service
metadata:
  name: passbolt-service
  labels:
    app: passbolt
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: passbolt
    tier: frontend
  type: ClusterIP
